[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
harmony_testnet = "${HARMONY_TESTNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
